# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.ActivityGroup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :name,
    :type,
    :includeCostPriceInFinance,
    :costAccountClosed,
    :costAccountOngoing,
    :costAccountOngoingType,
    :costContraAccountOngoing,
    :includeSalesPriceInFinance,
    :salesAccountClosed,
    :salesAccountOngoing,
    :salesAccountOngoingType,
    :salesContraAccountOngoing,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :name => String.t,
    :type => ActivityGroupType,
    :includeCostPriceInFinance => boolean() | nil,
    :costAccountClosed => integer() | nil,
    :costAccountOngoing => integer() | nil,
    :costAccountOngoingType => OngoingAccountType | nil,
    :costContraAccountOngoing => integer() | nil,
    :includeSalesPriceInFinance => boolean() | nil,
    :salesAccountClosed => integer() | nil,
    :salesAccountOngoing => integer() | nil,
    :salesAccountOngoingType => OngoingAccountType | nil,
    :salesContraAccountOngoing => integer() | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.ActivityGroup do
  import VismaEConomicOpenAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VismaEConomicOpenAPI.Model.ActivityGroupType, options)
    |> deserialize(:costAccountOngoingType, :struct, VismaEConomicOpenAPI.Model.OngoingAccountType, options)
    |> deserialize(:salesAccountOngoingType, :struct, VismaEConomicOpenAPI.Model.OngoingAccountType, options)
  end
end

