# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.CostTypeGroup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :name,
    :type,
    :markup,
    :accountOnGoing,
    :accountClosed,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer(),
    :name => String.t,
    :type => CostGroupType,
    :markup => float() | nil,
    :accountOnGoing => integer(),
    :accountClosed => integer(),
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.CostTypeGroup do
  import VismaEConomicOpenAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, VismaEConomicOpenAPI.Model.CostGroupType, options)
  end
end

