# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.CostType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :name,
    :costGroupNumber,
    :vatCode,
    :isBarred,
    :lastUpdated,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer(),
    :name => String.t,
    :costGroupNumber => integer(),
    :vatCode => String.t | nil,
    :isBarred => boolean() | nil,
    :lastUpdated => DateTime.t | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.CostType do
  def decode(value, _options) do
    value
  end
end

