# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.EmployeeGroup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :name,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer(),
    :name => String.t,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.EmployeeGroup do
  def decode(value, _options) do
    value
  end
end

