# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.MileagePrices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :costPrice,
    :costRate,
    :salesPrice,
    :salesRate
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :costPrice => float() | nil,
    :costRate => float() | nil,
    :salesPrice => float() | nil,
    :salesRate => float() | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.MileagePrices do
  def decode(value, _options) do
    value
  end
end

