# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.ProjectEmployee do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :groupNumber,
    :name,
    :isUser,
    :userId,
    :canApprove,
    :employeeType,
    :canInvoice,
    :isBarred,
    :address,
    :city,
    :zipCode,
    :cutOffDate,
    :salesPriceBefore,
    :salesPriceAfter,
    :costPriceBefore,
    :costPriceAfter,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer(),
    :groupNumber => integer(),
    :name => String.t,
    :isUser => boolean() | nil,
    :userId => String.t | nil,
    :canApprove => boolean(),
    :employeeType => EmployeeType | nil,
    :canInvoice => boolean(),
    :isBarred => boolean(),
    :address => String.t | nil,
    :city => String.t | nil,
    :zipCode => String.t | nil,
    :cutOffDate => Date.t | nil,
    :salesPriceBefore => float() | nil,
    :salesPriceAfter => float() | nil,
    :costPriceBefore => float() | nil,
    :costPriceAfter => float() | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.ProjectEmployee do
  import VismaEConomicOpenAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:employeeType, :struct, VismaEConomicOpenAPI.Model.EmployeeType, options)
    |> deserialize(:cutOffDate, :date, nil, options)
  end
end

