# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.TimeEntry do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :projectNumber,
    :activityNumber,
    :employeeNumber,
    :date,
    :text,
    :numberOfHours,
    :isApproved,
    :isReconciled,
    :lastUpdated,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :projectNumber => integer(),
    :activityNumber => integer(),
    :employeeNumber => integer(),
    :date => DateTime.t,
    :text => String.t | nil,
    :numberOfHours => float() | nil,
    :isApproved => boolean() | nil,
    :isReconciled => boolean() | nil,
    :lastUpdated => DateTime.t | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.TimeEntry do
  def decode(value, _options) do
    value
  end
end

