# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.TimeEntryPrices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :costPrice,
    :salesPrice
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :costPrice => float() | nil,
    :salesPrice => float() | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.TimeEntryPrices do
  def decode(value, _options) do
    value
  end
end

