# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.UpdateProjectActivityRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :projectNumber,
    :activityNumber,
    :startDate,
    :endDate,
    :responsibleEmployeeNumber,
    :completed,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :projectNumber => integer(),
    :activityNumber => integer(),
    :startDate => DateTime.t | nil,
    :endDate => DateTime.t | nil,
    :responsibleEmployeeNumber => integer() | nil,
    :completed => boolean() | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.UpdateProjectActivityRequest do
  def decode(value, _options) do
    value
  end
end

