# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.UpdateActivityRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :groupNumber,
    :name,
    :isAccessible,
    :inLieuCode,
    :hideInSearch,
    :cutoffDate,
    :salesPriceBefore,
    :salesPriceAfter,
    :costPriceMarkupPercentage,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer(),
    :groupNumber => integer(),
    :name => String.t,
    :isAccessible => boolean() | nil,
    :inLieuCode => integer() | nil,
    :hideInSearch => boolean() | nil,
    :cutoffDate => DateTime.t | nil,
    :salesPriceBefore => float() | nil,
    :salesPriceAfter => float() | nil,
    :costPriceMarkupPercentage => float() | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.UpdateActivityRequest do
  def decode(value, _options) do
    value
  end
end

