# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.UpdateEmployeeRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :number,
    :groupNumber,
    :name,
    :access,
    :phone,
    :email,
    :objectVersion
  ]

  @type t :: %__MODULE__{
    :number => integer() | nil,
    :groupNumber => integer(),
    :name => String.t,
    :access => boolean(),
    :phone => String.t | nil,
    :email => String.t | nil,
    :objectVersion => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.UpdateEmployeeRequest do
  def decode(value, _options) do
    value
  end
end

