# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule VismaEConomicOpenAPI.Model.ValidationProblemDetails do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :errors,
    :type,
    :title,
    :status,
    :detail,
    :instance
  ]

  @type t :: %__MODULE__{
    :errors => %{optional(String.t) => [String.t]} | nil,
    :type => String.t | nil,
    :title => String.t | nil,
    :status => integer() | nil,
    :detail => String.t | nil,
    :instance => String.t | nil
  }
end

defimpl Poison.Decoder, for: VismaEConomicOpenAPI.Model.ValidationProblemDetails do
  def decode(value, _options) do
    value
  end
end

